# Site settings

title: Deshebrando lo cotidiano
author: 
name: Betsabe Castro
email: leyla.ksl123@gmail.com
description: "Fragmentos filosóficos que nos conceden darle lectura a nuestra existencia"

# Build settings
theme: jekyll-theme-modernist
